image emotion_angry = "images/assets/Emotion/01.png"      # Image 01: Angry expression
image emotion_celebrate = "images/assets/Emotion/02.png"  # Image 02: Celebration (party popper)
image emotion_confused = "images/assets/Emotion/03.png"   # Image 03: Confusion (squiggly line)
image emotion_stressed = "images/assets/Emotion/04.png"   # Image 04: Stress marks
image emotion_music_note = "images/assets/Emotion/05.png" # Image 05: Music note
image emotion_love = "images/assets/Emotion/06.png"       # Image 06: Heart/love symbol
image emotion_tired = "images/assets/Emotion/07.png"      # Image 07: Sleepy/drowsy
image emotion_anger = "images/assets/Emotion/08.png"      # Image 08: Anger marks
image emotion_spiral = "images/assets/Emotion/09.png"     # Image 09: Dizzy/spiral
image emotion_sparkle = "images/assets/Emotion/010.png"   # Image 10: Sparkles
image emotion_worried = "images/assets/Emotion/011.png"   # Image 11: Worried cloud
image emotion_question = "images/assets/Emotion/012.png"  # Image 12: Question mark
image emotion_surprise = "images/assets/Emotion/013.png"  # Image 13: Surprise/exclamation marks
image emotion_shock = "images/assets/Emotion/014.png"     # Image 14: Shock or surprise (!)
image emotion_tear = "images/assets/Emotion/015.png"      # Image 15: Single tear (sadness)
image emotion_dots = "images/assets/Emotion/016.png"      # Image 16: Speechless (ellipsis/dots)